---
name: build-deb.yaml
on:
  push:
    branches:
      - feat-deb-action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Set up ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-rosdep python3-rosinstall-generator python3-vcstool
          sudo apt-get install -y python3-bloom devscripts fakeroot
          sudo rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build ROS workspace
        run: |
          source /opt/ros/noetic/setup.bash
          catkin_make

      - name: Generate debian/ directory and build .deb package
        run: |
          cd ./src/cobridge
          source /opt/ros/noetic/setup.bash        
          bloom-generate rosdebian --ros-distro noetic
          fakeroot debian/rules binary

      - name: Upload .deb package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


