name: build-deb.yaml
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS environment
        uses: ros-tooling/setup-ros@v0.2.2
        with:
          distribution: noetic

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper

      - name: Build Debian package
        run: |
          mkdir -p ~/debbuild/SOURCES
          cp -r . ~/debbuild/SOURCES/
          cd ~/debbuild/SOURCES
          dpkg-buildpackage -us -uc -b

      - name: Upload Debian package
        uses: actions/upload-artifact@v3
        with:
          name: coBridge-deb
          path: ~/debbuild/*.deb