name: Build and Test
on:
  pull_request:
  release:

permissions:
  contents: write
  packages: write

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [indigo, melodic, noetic, foxy, humble, jazzy]

    name: Build-And-Test (ROS ${{ matrix.ros_distribution }})
    runs-on: ubuntu-latest
    container:
      image: cobridge/ros-${{ matrix.ros_distribution }}:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Apply patches
        run: |
          cd src/cobridge
          ./patch_apply.sh

      - name: Build
        run: |
          make -f ./src/cobridge/Makefile build

      - name: Test
        run: |
          make -f ./src/cobridge/Makefile test
