name: Build runner
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-runner-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [foxy, noetic, humble]
    env:
      REGISTRY: hub.docker.com/cobridge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: cobridge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/ros-${{ matrix.ros_distribution }}
          tags: |
            type=raw,value={{ date 'now' 'YY.MM.DD' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./docker_files/${{ matrix.ros_distribution }}.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}