---
name: build deb
on:
  push:
    branches:
      - feat-deb-action
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [foxy, noetic]

    name: Build deb (ROS ${{ matrix.ros_distribution }})

    runs-on: ubuntu-20.04
    container:
      image: cobridge/ros-${{ matrix.ros_distribution }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Generate debian/ directory and build .deb package
        run: |
          rosdep update --include-eol-distros
          cd ./src/cobridge
          bloom-generate rosdebian --ros-distro noetic
          fakeroot debian/rules binary

      - name: Upload Artifacts with Dynamic Name
        run: |
          echo "ARTIFACT_NAME=$(basename $(find ./src -name '*.deb'))" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./src/*.deb
