name: Build and Test
on:
  pull_request:
  push:
    branches: [main, master]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [melodic, noetic, foxy, humble, jazzy, rolling]
        include:
          - ROS_DISTRO: indigo
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      AFTER_INIT: 'cd $TARGET_REPO_PATH && ./patch_apply.sh'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.ROS_DISTRO }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.ROS_DISTRO }}-
            
      - name: Run industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
