---
name: build deb
on:
  push:
    branches:
      - feat-deb-action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: cobridge/ros-noetic:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y python3-bloom devscripts fakeroot debhelper

      - name: Generate debian/ directory and build .deb package
        run: |
          rosdep update
          cd ./src/cobridge
          bloom-generate rosdebian --ros-distro noetic
          fakeroot debian/rules binary
          cd ..
          ls -lah
          cd ..
          ls -lah

      - name: Upload .deb package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


