name: build-and-test
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [foxy, noetic, humble]

    name: Build-And-Test (ROS ${{ matrix.ros_distribution }})
    runs-on: ubuntu-latest
    container:
      image: cobridge/ros-${{ matrix.ros_distribution }}:24.09.06
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Build
        run: |
          make -f ./src/cobridge/Makefile build

      - name: Test
        run: |
          make -f ./src/cobridge/Makefile test

      - name: zip-artifact
        run: zip -r install.zip install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.ros_distribution }}-cobridge
          path: install.zip
