name: build deb
on:
  push:
    branches:
      - feat-deb-action
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [foxy, humble, noetic]
        arch: [amd64, arm64]

    name: Build deb (ROS ${{ matrix.ros_distribution }} - ${{ matrix.arch }})

    runs-on: ubuntu-20.04
    container:
      image: cobridge/ros-${{ matrix.ros_distribution }}:latest

    steps:
      - name: Setup QEMU for ARM builds
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v2

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Generate debian/ directory and build .deb package
        run: |
          rosdep update --include-eol-distros
          cd ./src/cobridge
          bloom-generate rosdebian --ros-distro ${{ matrix.ros_distribution }}
          DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b -us -uc -a${{ matrix.arch }}

      - name: Upload Artifacts with Dynamic Name
        run: |
          echo "ARTIFACT_NAME=$(basename $(find ./src -name '*_${{ matrix.arch }}.deb'))" >> $GITHUB_ENV
          ls .. -lah

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./src/*_${{ matrix.arch }}.deb
