name: Build and Test
on:
  pull_request:
  release:
    types: [ published ]

permissions:
  contents: write
  packages: write

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [indigo, melodic, noetic, foxy, humble, jazzy, rolling]

    name: Build-And-Test (ROS ${{ matrix.ros_distribution }})
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.ros_distribution == 'rolling' && 'ros:rolling' || format('cobridge/ros-{0}:latest', matrix.ros_distribution) }}
    steps:
      - name: Checkout code
        if: matrix.ros_distribution != 'indigo' && matrix.ros_distribution != 'melodic'
        uses: actions/checkout@v4
        with:
          path: src/cobridge

      - name: Checkout code (indigo/melodic)
        if: matrix.ros_distribution == 'indigo' || matrix.ros_distribution == 'melodic'
        shell: bash
        run: |
          mkdir -p src/cobridge
          cd src/cobridge
          echo "current sha: ${{ github.sha}}, current ref: ${{ github.ref }}"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global --add safe.directory /__w/cobridge/cobridge
          
          git clone https://github.com/${{ github.repository }}.git .
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR number: ${{ github.event.pull_request.number }}"
            git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
            git checkout pr-branch
          else
            git checkout ${{ github.sha }}
          fi

      - name: Install dependencies (rolling only)
        if: matrix.ros_distribution == 'rolling'
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            libasio-dev zip ros-${ROS_DISTRO}-resource-retriever ros-${ROS_DISTRO}-cv-bridge \
            python3-bloom devscripts fakeroot debhelper apt-utils gnupg curl
          rm -rf /var/lib/apt/lists/*

      - name: Apply patches
        run: |          
          cd src/cobridge
          ./patch_apply.sh  

      - name: Build
        run: |
          make -f ./src/cobridge/Makefile build

      - name: Test
        run: |
          make -f ./src/cobridge/Makefile test
