name: build deb
on:
  push:
    branches:
      - feat-deb-action
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: noetic
            arch: amd64
            label: ubuntu-latest
            container: cobridge/ros-noetic:latest
#          - ros_distribution: noetic
#            arch: arm64
#            label: [ linux-arm-64-8c-32g-300gb ]
#            container: cobridge/ros-noetic:latest
#          - ros_distribution: foxy
#            arch: amd64
#            label: ubuntu-latest
#            container: cobridge/ros-foxy:latest
#          - ros_distribution: foxy
#            arch: arm64
#            label: [ linux-arm-64-8c-32g-300gb ]
#            container: cobridge/ros-foxy:latest
#          - ros_distribution: humble
#            arch: amd64
#            label: ubuntu-latest
#            container: cobridge/ros-humble:latest
#          - ros_distribution: humble
#            arch: arm64
#            label: [ linux-arm-64-8c-32g-300gb ]
#            container: cobridge/ros-humble:latest

    name: Build deb (ROS ${{ matrix.ros_distribution }} - ${{ matrix.arch }})

    runs-on: ${{ matrix.label }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Generate debian/ directory and build .deb package
        run: |
          rosdep update --rosdistro=${{ matrix.ros_distribution }}
          cd ./src/cobridge
          bloom-generate rosdebian --ros-distro ${{ matrix.ros_distribution }}
          DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b -us -uc -a${{ matrix.arch }}
          ls .. -lah

      - name: Get DEB file name
        run: |
          echo "ARTIFACT_NAME=$(basename $(find ./src -name '*_${{ matrix.arch }}.deb'))" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.ros_distribution }} - ${{ matrix.arch }}
          path: ./src/*.deb

      - name: Generate GPG Key
        run: |
          cat >key.conf <<EOF
          %echo Generating a GPG key
          Key-Type: RSA
          Key-Length: 2048
          Name-Real: CoScene
          Name-Email: coscene@coscene.io
          Expire-Date: 0
          %no-protection
          %commit
          %echo Done
          EOF

          gpg --batch --gen-key key.conf
          gpg --armor --export coscene@coscene.io > cobridge.gpg-key.asc
          ls -alh

      - name: Build APT repo
        run: |
          mkdir -p dists/stable/main/binary-${{ matrix.arch }}
          cp ./src/${{ env.ARTIFACT_NAME }} ./dists/stable/main/binary-${{ matrix.arch }}/${{ env.ARTIFACT_NAME }}
          dpkg-scanpackages dists/stable/main/binary-${{ matrix.arch }} /dev/null > dists/stable/main/binary-${{ matrix.arch }}/Packages          
          gzip -k -f dists/stable/main/binary-${{ matrix.arch }}/Packages
          apt-ftparchive release dists/stable > dists/stable/Release
          
          gpg --clearsign -o dists/stable/InRelease dists/stable/Release
          gpg -abs -o dists/stable/Release.gpg dists/stable/Release
          
          cat dists/stable/main/binary-${{ matrix.arch }}/Packages
          echo "\n----------------------------------\n"
          cat dists/stable/Release
          
          ls -alh
          
#
#          cp cobridge.gpg-key.asc ./apt/cobridge.gpg-key.asc
#          cd ./apt
#          dpkg-scanpackages -m . > Packages
#          apt-ftparchive release . > Release
#          gzip -k -f Packages
#          gpg --armor --detach-sign --sign -o Release.gpg Release
#          gpg --clearsign -o InRelease Release
#          ls -alh

      - name: Upload file to OSS
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ secrets.OSS_ARTIFACTS_ACCESS_KEY }}
          key-secret: ${{ secrets.OSS_ARTIFACTS_ACCESS_SECRET }}
          region: oss-cn-hangzhou
          bucket: coscene-download
          assets: |
            ./dists/stable/main/binary-${{ matrix.arch }}/${{ env.ARTIFACT_NAME }}:/coBridge/apt/cobridge/dists/stable/main/binary-${{ matrix.arch }}/${{ env.ARTIFACT_NAME }}
            ./dists/stable/main/binary-${{ matrix.arch }}/Packages:/coBridge/apt/cobridge/dists/stable/main/binary-${{ matrix.arch }}/Packages
            ./dists/stable/main/binary-${{ matrix.arch }}/Packages.gz:/coBridge/apt/cobridge/dists/stable/main/binary-${{ matrix.arch }}/Packages.gz
            ./dists/stable/Release:/coBridge/apt/cobridge/dists/stable/Release
            ./dists/stable/InRelease:/coBridge/apt/cobridge/dists/stable/InRelease
            ./dists/stable/Release.gpg:/coBridge/apt/cobridge/dists/stable/Release.gpg
