---
name: build deb
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: cobridge/ros-noetic:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: src/cobridge

      - name: Generate debian/ directory and build .deb package
        run: |
          rosdep update
          cd ./src/cobridge
          bloom-generate rosdebian --ros-distro noetic
          fakeroot debian/rules binary
          ls .. -lah

      - name: Upload Artifacts with Dynamic Name
        run: |
          echo "ARTIFACT_NAME=$(basename $(find ./src -name '*.deb'))" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./src/*.deb
