name: lint
on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: ros:foxy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run lint
        run: make lint
