name: lint
on:
  push:


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: registry.cn-hangzhou.aliyuncs.com/coscene/ros2-foxy-runner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    env:
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      GH_PACKAGES_ORG_TOKEN: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run lint
        run: make lint
